//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model.Entities
{
    using System;
    using System.Collections.Generic;
	using System.Data;

	public partial class HoaDon
    {
        public int? MaHoaDon { get; set; }
        public System.DateTime NgayGiaoDich { get; set; }
        public string MaDT { get; set; }
        public string LoaiHoaDon { get; set; }
        public decimal GiamGia { get; set; }
        public double TongTien { get; set; }

		public HoaDon()
		{

		}

		public HoaDon(DataRow row)
		{
            MaHoaDon = (int)row["MaHoaDon"];
            NgayGiaoDich = Convert.ToDateTime(row["NgayGiaoDich"]);
            MaDT = row["MaDT"].ToString();
            LoaiHoaDon = row["LoaiHoaDon"].ToString();
            GiamGia = decimal.Parse(row["GiamGia"].ToString());
            TongTien = (double)row["TongTien"];
        }

		public HoaDon(DateTime ngayGiaoDich, string maDT, string loaiHoaDon, decimal giamGia, double tongTien, int? maHoaDon = null)
		{
            MaHoaDon = maHoaDon;
            NgayGiaoDich = ngayGiaoDich;
            MaDT = maDT;
            LoaiHoaDon = loaiHoaDon;
            GiamGia = giamGia;
            TongTien = tongTien;    
		}
    }
}
