//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model.Entities
{
    using System;
    using System.Collections.Generic;
	using System.Data;

	public partial class Taikhoan
    {
        public string IDAccount { get; set; }
        public string Password { get; set; }
        public string TenTaiKhoan { get; set; }
        public string SDT { get; set; }
        public bool Active { get; set; }
        public string RoleID { get; set; }

		public Taikhoan()
		{

		}

        public Taikhoan(DataRow row)
        {
            IDAccount = row["IDAccount"].ToString();
            TenTaiKhoan = row["TenTaiKhoan"].ToString();
            SDT = row["SDT"].ToString();
            Active = (bool)row["Active"];
            RoleID = row["RoleID"].ToString();
        }
    }
}
