//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public int MaSP { get; set; }
        public string TacGia { get; set; }
        public string NamXB { get; set; }
        public string NhaXB { get; set; }
    }
}
