//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBiDienTu
    {
        public int MaSP { get; set; }
        public string MauSac { get; set; }
        public string ChatLieu { get; set; }
        public string BaoHanh { get; set; }
        public string ThongSoKiThuat { get; set; }
    }
}
